language: node_js
node_js:
    - "8.1.3"

before_install: yarn global add greenkeeper-lockfile

install:
    - yarn --frozen-lockfile
    
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
    - yarn hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: master
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: dev
    
notifications:
  email: false
