language: node_js
node_js:
    - "8.1.3"
    
branches:
    only:
    - dev

install:
    - yarn --frozen-lockfile

before_script:
    - git config --global user.name 'imcvampire'
    - git config --global user.email 'quocanh96@gmail.com'

script:
    - yarn deploy
    
