language: node_js
node_js:
    - "9"
    - "10"

before_install: 
    - npm install -g greenkeeper-lockfile
    - greenkeeper-lockfile-update

install:
    - npm install
    
after_script: greenkeeper-lockfile-upload

script:
    - npm run hexo generate

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: master
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: dev
    
notifications:
  email: false
