language: node_js
node_js:
    - "8.1.3"
    
branches:
    only:
    - dev

install:
    - yarn --frozen-lockfile

before_script:
    - git config --global user.name 'imcvampire'
    - git config --global user.email 'quocanh96@gmail.com'

script:
    - yarn hexo generate

after_success:
    - mkdir .deploy
    - cd .deploy
    - git init
    - git remote add origin $DEPLOY_REPO
    - cp -r ../public/* .
    - git add -A .
    - git commit -m 'Site updated'
    - git push --force --quiet origin master
    
