author: Bayo
description: Everyday life of Bayo Engineering
keyword: travel, bayo, engineering

excerpt_link: More...

menu:
 Posts: /
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

about:
  banner: http://file.muyutech.com/about.jpg
  avatar: https://static.bayo.vn/icon/applogo-256.png
  description: Everyday life of Bayo Engineering

