author: bayo-jsc
description: Bayo
keyword: travel, bayo, engineering

excerpt_link: More...

menu:
 Posts: /
 # About: /about

# highlight
highlight:
  tomorrow

# Gitment
# gitment_owner: yanm1ng
# gitment_repo: yanm1ng.github.io
# gitment_oauth_id: 0f87e490e00ee3fd87ef
# gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

about:
  banner: http://file.muyutech.com/about.jpg
  avatar: /images/avatar.png
  description: Everyday life of Bayo Engineering

