author: bayo-jsc
description: Bayo
keyword: travel, bayo, engineering

excerpt_link: More...

menu:
 Posts: /
 # About: /about/
 # Projects: /project/

# highlight
highlight:
  tomorrow

# Gitment
gitment_owner: imcvampire
gitment_repo: bayo-jsc.github.io
gitment_oauth_id: 1127ebf0f1ae6789773b
gitment_oauth_secret: f7e8b52d23049229a00a23f2ede517880ed89329

about:
  banner: http://file.muyutech.com/about.jpg
  avatar: /images/avatar.png
  description: Everyday life of Bayo Engineering

