author: bayo-jsc
description: Bayo
keyword: travel, bayo, engineering

excerpt_link: More...

menu:
 Posts: /
 # About: /about/
 # Projects: /project/

# highlight
highlight:
  tomorrow

# Gitment
gitment_owner: bayo-jsc
gitment_repo: bayo-jsc.github.io
gitment_oauth_id: 1127ebf0f1ae6789773b
gitment_oauth_secret: b417b808bc2e37a462456b7c7bc58c3da110142f

about:
  banner: http://file.muyutech.com/about.jpg
  avatar: /images/avatar.png
  description: Everyday life of Bayo Engineering

