author: Bayo
description: Everyday life of Bayo Engineering
keyword: travel, bayo, engineering

excerpt_link: More...

menu:
 Posts: /
 # About: /about/
 # Projects: /project/

# highlight
highlight:
  tomorrow

about:
  banner: http://file.muyutech.com/about.jpg
  avatar: /images/avatar.png
  description: Everyday life of Bayo Engineering

